### PR TITLE
Refactored Code using ES2015

### PR DESCRIPTION
**Pull request by aparker22**
@BGamber

### CODE REVIEW

**Comment by aparker22** [comment]
@pmattam

**Review by BGamber — COMMENTED** [review]
I'm seeing "File renamed without changes" for this commit; does this branch include changes from your previous version of code?

**Comment by aparker22** [comment]
@BGamber I did open a pull request with few changes, but you should be able to open up the commit to view the whole file

**Comment by BGamber** [comment]
I see you're working with file writing, nice! How well is that splice working for your delete function?

**Comment by aparker22** [comment]
@BGamber It deletes what I want it to delete!

**Comment by BGamber** [comment]
Nice.

Your router function server-side looks good. The findIfPathIncludesID function seems a little redundant... it returns the url without the id if it is there, but findPath returns the url without the id again if they visit '/contacts'. Have you checked out the String.startswith() function? It would likely handle that "id is or is not included" case for you.

**Pull request merged**
